# costmap:
#   costmap:
#     ros__parameters:
#       update_frequency: 5.0
#       publish_frequency: 2.0
#       global_frame: odom
#       robot_base_frame: base_link
#       use_sim_time: False
#       rolling_window: true
#       width: 3
#       height: 3
#       resolution: 0.05
#       robot_radius: 0.22
#       plugins: ["voxel_layer", "inflation_layer"]
#       inflation_layer:
#         plugin: "nav2_costmap_2d::InflationLayer"
#         cost_scaling_factor: 3.0
#         inflation_radius: 0.55
#       voxel_layer:
#         plugin: "nav2_costmap_2d::VoxelLayer"
#         enabled: True
#         publish_voxel_map: True
#         origin_z: 0.0
#         z_resolution: 0.05
#         z_voxels: 16
#         max_obstacle_height: 2.0
#         mark_threshold: 0
#         observation_sources: pointcloud
#         pointcloud:
#           topic: /camera/depth/color/points
#           max_obstacle_height: 2.0
#           clearing: True
#           marking: True
#           data_type: "PointCloud2"
#       static_layer:
#         map_subscribe_transient_local: True
#       always_send_full_costmap: True
#   costmap_client:
#     ros__parameters:
#       use_sim_time: False
#   costmap_rclcpp_node:
#     ros__parameters:
#       use_sim_time: False
costmap:
  costmap:
    ros__parameters:
      global_frame: odom
      robot_base_frame: base_link
      update_frequency: 5.0
      publish_frequency: 1.0
      use_sim_time: False

      #set if you want the voxel map published
      publish_voxel_map: true

      #set to true if you want to initialize the costmap from a static map
      static_map: false

      #begin - COMMENT these lines if you set static_map to true
      rolling_window: true
      width: 6.0
      height: 6.0
      resolution: 0.025
      #end - COMMENT these lines if you set static_map to true

      #START VOXEL STUFF
      map_type: voxel
      origin_z: 0.0
      z_resolution: 0.2
      z_voxels: 10
      unknown_threshold: 10
      mark_threshold: 0
      #END VOXEL STUFF

      transform_tolerance: 0.3
      obstacle_range: 2.5
      max_obstacle_height: 2.0
      raytrace_range: 3.0
      #footprint: [[-0.325, -0.325], [-0.325, 0.325], [0.325, 0.325], [0.46, 0.0], [0.325, -0.325]]
      #robot_radius: 0.46
      footprint_padding: 0.01
      inflation_radius: 0.55
      cost_scaling_factor: 10.0
      lethal_cost_threshold: 100
      #observation_sources: base_scan
      #base_scan: {data_type: LaserScan, expected_update_rate: 0.4,
      #  observation_persistence: 0.0, marking: true, clearing: true, max_obstacle_height: 0.4, min_obstacle_height: 0.08}
      plugins: ["static_layer","voxel_layer", "inflation_layer"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_topic: "/univloc_server/map"
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.55
      voxel_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: True
        publish_voxel_map: True
        origin_z: 0.0
        z_resolution: 0.05
        z_voxels: 16
        max_obstacle_height: 2.0
        mark_threshold: 0
        observation_sources: pointcloud
        pointcloud:
          topic: /camera/depth/color/points
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "PointCloud2"
      static_layer:
        map_subscribe_transient_local: True
      always_send_full_costmap: True
  costmap_client:
    ros__parameters:
      use_sim_time: False
  costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: False
